### ISSUE TITLE
[webp] alpha support?

### ISSUE THREAD

**Issue by nnmrts** [saschazar21/webassembly#125]
First of all, thanks for this module, works great.

One "small" thing missing for me is alpha support, and I'll suggest below how to implement it, if I understood your project architecture correctly.

Alright, so I found out encoding an image with an alpha channel to webp doesn't work, the output looks grey and "tripled" somehow. So unfortunately, in order to encode an RGBA buffer, I have to remove every fourth byte from it, effectively losing the whole alpha channel.

I don't know, but I believe you are using `WebPEncodeRGB` internally, right? I would suggest using `WebPEncodeRGBA` (or even better `WebPEncodeLosslessRGBA` if that's possible). In order to keep your API backwards compatible, so that users can still input just RGB buffers in `wasm_webp.encode`, I would suggest adding an`wasm_webp.encodeRGBA` method, where you could input an RGBA buffer. Another solution would be to add a simple `format` argument to the standard `encode` method which defaults to "RGB", but when set to "RGBA" it uses `WebPEncodeRGBA` instead of `WebPEncodeRGB`.

On a side note, it would be great (although I don't know if that's even allowed and/or possible) if you could provide the actual API file (with the definition of the `encode` method for example) in the repository. I don't know exactly how wasm compiling works but it would be great for users to be able to suggest changes to those methods (by pull requests for example).

Stay safe! 💯 

EDIT: whoops, I just "discovered" the main.cpp file, haha. Hm.

**Comment by saschazar21** [comment]
Hi @nnmrts - glad you reached out! 👋 

The reason why most of the included packages lack the alpha channel is the fact, that I haven't had any need for it yet.

However, I get the idea, why it might be useful (peeking at `<canvas />`). The only thing, which I'm not that sure yet, is whether adding an additional function would be the right idea...

I'd like to keep it as small as possible (to improve support for browser environments), and of course; as backwards-compatible as possible...

I'll try to fiddle around a bit during the next days—of course you're welcome to do so too!

PS: All of my repositories are 💯% open source, so whenever a file seems to be missing, it is definitely unintended.

**Comment by saschazar21** [comment]
Hi @nnmrts - sorry it took so long. But new major releases of all packages are now available.

Each decoder and encoder is now supporting a `channels` function argument, meaning you get the option to tell the decoder, how many channels you like to get out (some decoders are lacking an alpha channel output, e.g. `jpeg`).

Same goes for the encoder; you now have the possibility of either sending in `RGB` or `RGBA` buffers.

Hope the update fits your needs. If there's something else missing - let me know. Closing this issue now.

Stay safe!

**Comment by nnmrts** [comment]
@saschazar21 Wow, very nice, thanks!
