### ISSUE TITLE
Bad Magic Number

### ISSUE THREAD

**Issue by pbreah** [saschazar21/webassembly#444]
@saschazar21  thanks for the work so far with this lib. I have attempted to load wasm_image_loader.wasm on the browser, and gives the "Bad magic number" error - my guess would be this is related to the build since it works in node.

Have you tested loading it in the browser? I'm trying to replicate this same sample code (https://runkit.com/saschazar21/5e8746e3c924510013db78f4) you have with nodejs but in this case using the browser. 

Would love to see your sample code working on CodeSanbox if possible.

**Comment by saschazar21** [comment]
Hi @pbreah - thanks for reaching out.

I have to say I'm sorry, but it's a bit difficult for me to track your issue based on a single error message. I updated an existing CodeSandbox based on your use case today, so please have a look at [CodeSandbox](https://codesandbox.io/s/image-decoder-56ujt?file=/public/jpeg.js).

However, I have to admit, that I never used the `.wasm` binaries standalone so far—I can confirm they are working in the browser environment together with their glue code though (as the CodeSandbox shows).

Hopefully you'll find a suitable solution using the provided CodeSandbox—if that doesn't support you in your issue, it would be nice to have a look at your source code.

**Comment by pbreah** [comment]
The error came from the browser while loading the .wasm file, but I was loading it differently than your CodeSandbox example. That example answered all questions about loading, making it available and ready to use - that example was the key part I wanted to see. So many ways to do it, until finding the right way.  🎉 

One more star for you! thanks!
